export const imageLinks = [
    { name: 'ban-ran-man.jpg', link: 'https://iili.io/doxOgTb.jpg' },
    { name: 'banh-beo-chen.jpg', link: 'https://iili.io/doxeEPV.jpg' },
    { name: 'banh-bot-loc.jpg', link: 'https://iili.io/doxMcZP.png'},
    { name: 'banh-canh.jpg', link: 'https://iili.io/doxehHF.jpg' },
    { name: 'banh-com.jpg', link: 'https://iili.io/doxM0n1.png' },
    { name: 'banh-beo-chen.jpg', link: 'https://iili.io/doxeEPV.jpg' },
    { name: 'banh-beo.jpg', link: 'https://iili.io/doxe79e.png' },
    { name: 'banh-beo-ngot-nuoc-cot-dua.jpg', link: 'https://iili.io/doxMh9R.png' },
    { name: 'banh-dau-xanh.jpg', link: 'https://iili.io/doxe3FI.jpg' },
    { name: 'banh-đau-xanh.jpg', link: 'https://iili.io/doxe3FI.jpg' },
    { name: 'banh-da-lon.jpg', link: 'https://iili.io/doxeUlI.jpg' },
    { name: 'banh-duc-nong.jpg', link: 'https://iili.io/doxeWS1.jpg' },
    { name: 'banh-gai.jpg', link: 'https://iili.io/doxe0ox.jpg' },
    { name: 'banh-it.jpg', link: 'https://iili.io/doxeK8X.jpg' },
    { name: 'banh-it-tran.jpg', link: 'https://iili.io/doxectj.jpg' },
    { name: 'banh-ít.jpg', link: 'https://iili.io/doxeK8X.jpg' },
    { name: 'banh-ít-tran.jpg', link: 'https://iili.io/doxectj.jpg' },
    { name: 'banh-khot.jpg', link: 'https://iili.io/doxewNa.jpg' },
    { name: 'banh-mi-thit-nuong.jpg', link: 'https://iili.io/doxOmua.jpg' },
    { name: 'banh-mi-thit.jpg', link: 'https://iili.io/doxeawb.webp' },
    { name: 'banh-phong-tom.jpg', link: 'https://iili.io/doxe1MQ.jpg' },
    { name: 'banh-pia.jpg', link: 'https://iili.io/doxOPCQ.jpg' },
    { name: 'banh-tet.jpg', link: 'https://iili.io/doxOt8F.png' },
    { name: 'banh-tom-ho-tay.jpg', link: 'https://iili.io/doxOyZv.webp' },
    { name: 'banh-trang-nuong.jpg', link: 'https://iili.io/doxeYAu.jpg' },
    { name: 'banh-troi-tau.jpg', link: 'https://iili.io/doxeVcP.jpg' },
    { name: 'banh-trang-tron.jpg', link: 'https://iili.io/doxeeov.jpg' },
    { name: 'banh-xeo.jpg', link: 'https://iili.io/doxOQ3P.jpg' },
    { name: 'bun-bo-hue.jpg', link: 'https://iili.io/doxejAg.jpg' },
    { name: 'bun-ca.jpg', link: 'https://iili.io/doxezMl.jpg' },
    { name: 'bun-cha-ca.jpg', link: 'https://iili.io/doxexn4.jpg' },
    { name: 'bun-cha.jpg', link: 'https://iili.io/doxeSKN.jpg' },
    { name: 'bun-moc.jpg', link: 'https://iili.io/doxeRS9.jpg' },
    { name: 'bun-oc.jpg', link: 'https://iili.io/doxed6N.jpg' },
    { name: 'bun-ốc.jpg', link: 'https://iili.io/doxed6N.jpg' },
    { name: 'bun-rieu.jpg', link: 'https://iili.io/doxOpwJ.jpg' },
    { name: 'bun-thit-nuong.jpg', link: 'https://iili.io/doxOZa1.jpg' },
    { name: 'thit-nuong.jpg', link: 'https://iili.io/doxMwwN.png' },
    { name: 'bun-thang.jpg', link: 'https://iili.io/doxegSt.jpg' },
    { name: 'canh-chua-ca.jpg', link: 'https://iili.io/doxe4HX.jpg' },
    { name: 'cha-ca-la-vong.jpg', link: 'https://iili.io/doxeHnR.jpg' },
    { name: 'cha-muc.jpg', link: 'https://iili.io/doxevPp.jpg' },
    { name: 'chao-ga.jpg', link: 'https://iili.io/doxOiGV.jpg' },
    { name: 'chao-luon.jpg', link: 'https://iili.io/doxOSyu.webp' },
    { name: 'com-tam.jpg', link: 'https://iili.io/doxeMKB.jpg' },
    { name: 'goi-cuon.jpg', link: 'https://iili.io/doxeNDJ.jpg' },
    { name: 'lau-ga-la-giang.jpg', link: 'https://iili.io/doxeuFS.jpg' },
    { name: 'mi-quang.jpg', link: 'https://iili.io/doxeBus.jpg' },
    { name: 'pho-bo.jpg', link: 'https://iili.io/doxeAc7.jpg' },
    { name: 'nem-ran-(cha-gio).jpg', link: 'https://iili.io/doxMSFs.png' },
    { name: 'cha-gio-re.jpg', link: 'https://iili.io/doxMkMX.png' },
    { name: 'banh-cuon.jpg', link: 'https://iili.io/doxMvPn.png'},
    { name: 'banh-đuc-nong.jpg', link: 'https://iili.io/doxMent.png'},
    { name: 'bun-mam.jpg', link: 'https://iili.io/doxMjup.png'},
    { name: 'canh-bau-nau-tom.jpg', link: 'https://iili.io/doxMW8v.png' },
    { name: 'che-troi-nuoc.jpg', link: 'https://iili.io/doxMawB.png'},
    { name: 'canh-kho-qua-nhoi-thit.jpg', link: 'https://iili.io/doxMYuV.png'},
    { name: 'about-image.jpg', link: 'https://iili.io/doxbimJ.jpg'},
    { name: 'logo-spotlight.jpg', link: 'https://iili.io/doxbPea.png'},
    { name: 'premium-why.jpg', link: 'https://iili.io/doxbLzv.jpg'},
    { name: 'momo.jpg', link: 'https://iili.io/doxMI6u.png'},
  ];
  