export const imageLinks = [
    { name: 'ban-ran-man.jpg', link: 'https://i.ibb.co/J2nnybt/ban-ran-man.jpg' },
    { name: 'banh-beo-chen.jpg', link: 'https://i.ibb.co/sscKRb5/banh-beo-chen.jpg' },
    { name: 'banh-bot-loc.jpg', link: 'https://i.ibb.co/TR8KDXK/banh-bot-loc.png'},
    { name: 'banh-canh.jpg', link: 'https://i.ibb.co/rsjypgQ/banh-canh.jpg' },
    { name: 'banh-com.jpg', link: 'https://i.ibb.co/qJsZ2Wf/banh-com.png' },
    { name: 'banh-beo-chen.jpg', link: 'https://i.ibb.co/7Js4v5d/banh-beo.png' },
    { name: 'banh-beo.jpg', link: 'https://i.ibb.co/7Js4v5d/banh-beo.png' },
    { name: 'banh-beo-ngot-nuoc-cot-dua.jpg', link: 'https://i.ibb.co/5nCXnZ7/banh-beo-ngot.png' },
    { name: 'banh-dau-xanh.jpg', link: 'https://i.ibb.co/8g322pN/banh-dau-xanh.jpg' },
    { name: 'banh-đau-xanh.jpg', link: 'https://i.ibb.co/8g322pN/banh-dau-xanh.jpg' },
    { name: 'banh-da-lon.jpg', link: 'https://i.ibb.co/5rjVF8Y/banh-da-lon.jpg' },
    { name: 'banh-duc-nong.jpg', link: 'https://i.ibb.co/DCmVzgs/banh-duc-nong.jpg' },
    { name: 'banh-gai.jpg', link: 'https://i.ibb.co/SmXf0BF/banh-gai.jpg' },
    { name: 'banh-it.jpg', link: 'https://i.ibb.co/R4VVtGc/banh-it.jpg' },
    { name: 'banh-it-tran.jpg', link: 'https://i.ibb.co/T88fCxZ/banh-it-tran.jpg' },
    { name: 'banh-ít.jpg', link: 'https://i.ibb.co/R4VVtGc/banh-it.jpg' },
    { name: 'banh-ít-tran.jpg', link: 'https://i.ibb.co/T88fCxZ/banh-it-tran.jpg' },
    { name: 'banh-khot.jpg', link: 'https://i.ibb.co/3FK9d4R/banh-khot.jpg' },
    { name: 'banh-mi-thit-nuong.jpg', link: 'https://i.ibb.co/Mh2XhxS/banh-mi-thit-nuong.jpg' },
    { name: 'banh-mi-thit.jpg', link: 'https://i.ibb.co/k5SBtJ3/banh-mi-thit.webp' },
    { name: 'banh-phong-tom.jpg', link: 'https://i.ibb.co/vLXRkLV/banh-phong-tom.jpg' },
    { name: 'banh-pia.jpg', link: 'https://i.ibb.co/26H7LjS/banh-pia.jpg' },
    { name: 'banh-tet.jpg', link: 'https://i.ibb.co/yyWxQzj/banh-tet.png' },
    { name: 'banh-tom-ho-tay.jpg', link: 'https://i.ibb.co/Kmk8DWx/banh-tom-ho-tay.webp' },
    { name: 'banh-trang-nuong.jpg', link: 'https://i.ibb.co/mGFqRq1/banh-trang-nuong.jpg' },
    { name: 'banh-troi-tau.jpg', link: 'https://i.ibb.co/7jzrVTx/banh-troi-tau.jpg' },
    { name: 'banh-trang-tron.jpg', link: 'https://i.ibb.co/K2JP2hR/banh-trang-tron.jpg' },
    { name: 'banh-xeo.jpg', link: 'https://i.ibb.co/NZ7mssG/banh-xeo.jpg' },
    { name: 'bun-bo-hue.jpg', link: 'https://i.ibb.co/fn3q1cT/bun-bo-hue.jpg' },
    { name: 'bun-ca.jpg', link: 'https://i.ibb.co/9wgsjwS/bun-ca.jpg' },
    { name: 'bun-cha-ca.jpg', link: 'https://i.ibb.co/LQ3F2F7/bun-cha-ca.jpg' },
    { name: 'bun-cha.jpg', link: 'https://i.ibb.co/k10SXnb/bun-cha.jpg' },
    { name: 'bun-moc.jpg', link: 'https://i.ibb.co/TRf242F/bun-moc.jpg' },
    { name: 'bun-oc.jpg', link: 'https://i.ibb.co/YNV4pVq/bun-oc.jpg' },
    { name: 'bun-ốc.jpg', link: 'https://i.ibb.co/YNV4pVq/bun-oc.jpg' },
    { name: 'bun-rieu.jpg', link: 'https://i.ibb.co/Lr2HnPt/bun-rieu.jpg' },
    { name: 'bun-thit-nuong.jpg', link: 'https://i.ibb.co/zh6h8P5/bun-thit-nuong.jpg' },
    { name: 'thit-nuong.jpg', link: 'https://i.ibb.co/0JJs6G3/thit-nuong.png' },
    { name: 'bun-thang.jpg', link: 'https://i.ibb.co/my0Z3zZ/bun-thang.jpg' },
    { name: 'canh-chua-ca.jpg', link: 'https://i.ibb.co/c6sYLB9/canh-chua-ca.jpg' },
    { name: 'cha-ca-la-vong.jpg', link: 'https://i.ibb.co/1T1p91L/cha-ca-la-vong.jpg' },
    { name: 'cha-muc.jpg', link: 'https://i.ibb.co/WWTpGqt/cha-muc.jpg' },
    { name: 'chao-ga.jpg', link: 'https://i.ibb.co/pJb45Nh/chao-ga.jpg' },
    { name: 'chao-luon.jpg', link: 'https://i.ibb.co/HqrKv9M/chao-luon.webp' },
    { name: 'com-tam.jpg', link: 'https://i.ibb.co/dMd5gX1/com-tam.jpg' },
    { name: 'goi-cuon.jpg', link: 'https://i.ibb.co/1MJwZXN/goi-cuon.jpg' },
    { name: 'lau-ga-la-giang.jpg', link: 'https://i.ibb.co/7NLQ9sF/lau-ga-la-giang.jpg' },
    { name: 'mi-quang.jpg', link: 'https://i.ibb.co/CBJwcYr/mi-quang.jpg' },
    { name: 'pho-bo.jpg', link: 'https://i.ibb.co/yhGv6c7/pho-bo.jpg' },
    { name: 'nem-ran-(cha-gio).jpg', link: 'https://i.ibb.co/VLPzxCf/cha-gio.png' },
    { name: 'cha-gio-re.jpg', link: 'https://i.ibb.co/BBqzWZs/cha-gio-re.png' },
    { name: 'banh-cuon.jpg', link: 'https://i.ibb.co/FDcTj7D/banh-cuon.png'},
    { name: 'banh-đuc-nong.jpg', link: 'https://i.ibb.co/whKCwFv/banh-duc.png'},
    { name: 'bun-mam.jpg', link: 'https://i.ibb.co/Lzz9hqD/bun-mam.png'},
    { name: 'canh-bau-nau-tom.jpg', link: 'https://i.ibb.co/phqFzdX/canh-bau-nau-tom.png' },
    { name: 'che-troi-nuoc.jpg', link: 'https://i.ibb.co/6y1bYGr/che-troi-nuoc.png'},
    { name: 'canh-kho-qua-nhoi-thit.jpg', link: 'https://i.ibb.co/Zx5rCPn/canh-kho-qua-nhoi-thit.png'},
    { name: 'about-image.jpg', link: 'https://i.ibb.co/2y0Z81s/about-img.jpg'},
    { name: 'logo-spotlight.jpg', link: 'https://i.ibb.co/XpP2QLy/image.png'},
    { name: 'premium-why.jpg', link: 'https://i.ibb.co/2yXw527/premium-why.jpg'},
    { name: 'momo.jpg', link: 'https://i.ibb.co/6Y8pmY3/momo.png'},
  ];
  